apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m" # Set CPU resource request to 100m
          limits:
            cpu: "100m" # Add CPU resource limit to 100m
            memory: "64Mi" # Add memory resource limit to 64Mi
